version: '3.8'
services:
  train_service:
    image: arun280/train_cpp      
    ports:
      - "9091:9091"
  data_service:
    image: arun280/train_python
    ports:
      - "9090:9090"
    environment:
      - MYSQL_HOST=db  

  db:                         
    image: mysql           
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: railway
      MYSQL_USER: arun
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
